#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ifaddrs.h>

// for ip read/convert
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#include "loggy.h"
#include "limbonet.h"

char* _LIMBONET_LOGGY = "Network";

void limbonet_write(const char *wifiName, const char *wifiPass) {
  char *filepath = "/etc/netctl/limboradio";
  loggy_info(_LIMBONET_LOGGY, "Writing wifi netctl config to file %s.", filepath);
  FILE *fp = fopen(filepath, "w");
  if(fp == NULL) {
    loggy_error(_LIMBONET_LOGGY, "Failed. Cannot open file for write: %s.", filepath);
    return;
  }

  fprintf(fp, "Description='Generated by LimboRadio'\n");
  fprintf(fp, "Interface=wlan0\n");
  fprintf(fp, "Connection=wireless\n");
  fprintf(fp, "Security=wpa\n");
  fprintf(fp, "IP=dhcp\n");
  fprintf(fp, "Priority=10\n");
  fprintf(fp, "ESSID=\'%s\'\n", wifiName);
  fprintf(fp, "Key=\'%s\'\n", wifiPass);
  fclose(fp);
}

void limbonet_reset() {
  loggy_info(_LIMBONET_LOGGY, "Restarting netctl wifi (netctl-auto@wlan0)....");
  int rc = system("systemctl restart netctl-auto@wlan0");
  loggy_info(_LIMBONET_LOGGY, "Restarted netctl wifi (netctl-auto@wlan0) with RC: %d.", rc);
}

void limbonet_info(char *output) {
  loggy_debug(_LIMBONET_LOGGY, "Reading network info.");

  struct ifaddrs *ifa, *ifStart;
  if(getifaddrs(&ifStart)) {
    strcpy(output, "Check error");
    return;
  }

  // Read both (wifi and lan) and return best/available
  char adrEth4[INET_ADDRSTRLEN] = "";
  char adrWifi4[INET_ADDRSTRLEN] = "";

  ifa = ifStart;
  while(ifa != NULL) {
    char *ifName = ifa->ifa_name;
    struct sockaddr *ifAddr = ifa->ifa_addr;

    char *adrTarget = NULL;
    if(strcmp("eth0",ifName) == 0) adrTarget = adrEth4;
    else if(strcmp("wlan0",ifName) == 0) adrTarget = adrWifi4;
    else {
      ifa = ifa->ifa_next;
      continue;
    }

    switch(ifAddr->sa_family) {
        case AF_INET: {
            struct sockaddr_in *addr_in = (struct sockaddr_in *)ifAddr;
            char adrString[INET_ADDRSTRLEN];
            inet_ntop(AF_INET, &(addr_in->sin_addr), adrString, INET_ADDRSTRLEN);
            inet_ntop(AF_INET, &(addr_in->sin_addr), adrTarget, INET_ADDRSTRLEN);
            loggy_debug(_LIMBONET_LOGGY, "Network %s - IPv4: %s", ifa->ifa_name, adrString);
            break;
        }
        case AF_INET6: {
            struct sockaddr_in6 *addr_in6 = (struct sockaddr_in6 *)ifAddr;
            char adrString[INET6_ADDRSTRLEN];
            inet_ntop(AF_INET6, &(addr_in6->sin6_addr), adrString, INET6_ADDRSTRLEN);
            loggy_debug(_LIMBONET_LOGGY, "Network %s - IPv6: %s", ifa->ifa_name, adrString);
            break;
        }
        default:
            break;
    }

    ifa = ifa->ifa_next;
  }

  if(strcmp("",adrWifi4) != 0) {
    strcpy(output, adrWifi4);
  }
  else if(strcmp("",adrEth4) != 0) {
    strcpy(output, adrEth4);
  }
  else {
    strcpy(output, "Disconnected");
  }

  freeifaddrs(ifStart);
}
